module.exports = {

  username: 'SYSADMIN',
  password: 'SYSADMINZebra@123!',
  projectTypeName: "Program Project : Sanity : KNLDEV01",
  projectTypeDescription: "Program Project : Sanity : KNLDEV01",
  projectTitle: `Program Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  projectTitleEdit : `Post Launch Edit Program Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  assignTo: "Store Manager - Store",
  assignTo1: "Store Manager - Grocery",
  creatorDept: "Corporate",
  tags: "AutoProgramSanity",
  tags2: "PostLaunchEdit",
  projectNotes: "Notes For Project",
  projectNotesEdit: "Post launch edit Notes",
  attachmentFile: 'C:\\PlaywrightAutomation\\PlayWright\\Attachments\\file.pdf',
  taskTitle: "Task 1",
  taskTitle1: "Task 2",
  specificStore: "AN1,7070,8080,ZebraX1,ZebraX2",
  projectLaunchComment: "Project Launch",
  simpleProjectType: "Simple Project - Update Store KNLDEV01",
  simpleProjectTitle: `Simple Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  SimpleProjectTitleEdit : `Post Launch Edit Simple Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  simpleRepeatingProjectTitle: `Simple Sanity Repeating : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  simpleRepeatingProjectTitleEdit:`EDIT Simple Sanity Repeating : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  collaborationProjectType: "Collaboration Project - KNLDEV01",
  collaborationProjectTitle: `Collaboration Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  collaborationProjectTitleEdit : `Post Launch Edit Collaboration Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  collaboTaskStore: `Task ${Math.floor(Math.random() * 100000)} : Store`,
  collaboTaskStore1: `Task ${Math.floor(Math.random() * 100000)} : Store`,
  collaboTaskCorporate: `Task ${Math.floor(Math.random() * 100000)} : Corporate`,
  executionLevelStore: "Store",
  executionLevelCorporate: "Corporate",
  assignToCorporate : "Approver - Corporate",
  simpleRepeatingType: "Simple Repeating Project - Update Store KNLDEV01",
  repeatingProjectType: "Repeating Project : KNLDEV01",
  repeatingProjectTitle: `Repeating Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  repeatingProjectTitleEdit :`EDIT Repeating Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  calendarProjectType: "Calendar Project - KNLDEV01",
  calendarProjectTitle:`Calendar Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  calendarProjectTitleEdit:`Post Edit Calendar Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  planProjectType: "Plan For Plan Processing KNLDEV01",
  planProjectTitle:`Plan Project Sanity : TASK-RELEASE ${Math.floor(Math.random() * 100000)}`,
  planningDept: "Store",
  planCategory : "Product 6 - Recall",
  resourceType : "Store Manager",
  resourceDepartment: "Store",
  postComment: "Changes",
  organizationLevel: "Corporate",
  assignToCorp: "Approver - Corporate",
  corpStore: "CORP",

  };